import type { NextPage } from "next";
import Head from "next/head";
import { GetStaticProps } from "next";
import { PrismaClient } from "@prisma/client";
import { GraphQLClient, gql } from "graphql-request";

export const getStaticProps: GetStaticProps = async () => {
	//product hunt fetch
	const endpoint = "https://api.producthunt.com/v2/api/graphql";
	const graphQLClient = new GraphQLClient(endpoint, {
		headers: {
			authorization: `Bearer ${process.env.DEV_TOKEN}`,
		},
	});
	const query = gql`
		{
			posts(postedAfter: "2022-01-11T02:42:00.843Z", order: VOTES) {
				edges {
					node {
						id
						tagline
						votesCount
						website
						description
					}
				}
			}
		}
	`;
	const productHuntPosts = await graphQLClient.request(query);

	//prisma mongoDb fetch
	const prisma = new PrismaClient();
	const snippet = await prisma.codesnippets.findMany();

	const serializedSnippets = snippet.map((codeSnippet) => {
		return {
			...codeSnippet,
			createdAt: codeSnippet?.createdAt.toISOString(),
		};
	});

	return {
		props: { productHuntPosts, serializedSnippets },
	};
};

interface Snippet {
	id: string;
	createdAt: string;
	title: string;
	prompt: string;
	language: string;
	category: string;
	difficulty: string;
	solution: string;
}
interface Props {
	snippet: Snippet;
	productHuntPosts: any;
}
interface Post {
	id: string;
	tagline: string;
	votesCount: number;
	website: string;
	description: string;
}

const Home: NextPage<Props> = ({ snippet, productHuntPosts }) => {
	console.log(
		"productHuntPosts",
		productHuntPosts.posts.edges.map((edge: any) => edge.node)
	);

	const posts: Post[] = productHuntPosts.posts.edges.map((edge: { node: Post[] }) => edge.node);
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="flex flex-col items-center justify-center h-screen">
				{posts.map((post) => (
					<div key={post.id}>
						{post.tagline}
						{post.votesCount}
					</div>
				))}
			</div>
		</>
	);
};

export default Home;
