import type { NextPage } from "next";
import Head from "next/head";
import { GetStaticProps } from "next";
import { PrismaClient } from "@prisma/client";

export const getStaticProps: GetStaticProps = async () => {
	const prisma = new PrismaClient();
	const snippets = await prisma.codeSnippet.findMany();
	return {
		props: { snippets },
	};
};

interface Snippet {
    id: String;
    createdAt: Date;
    title: String;
    prompt: String;
    language: String;
    category: String;
    difficulty: String;
    solution: String;
    solved: Boolean[];
  }
interface Props {
  snippets: Snippet[]
}

const Home: NextPage<Props> = (props) => {
  console.log(props)
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
      <div>
        Hello!!!!
      </div>
		</>
	);
};

export default Home;
